# Define samples
samples:
# tRNA dominant
    NSUN2_HEK293T_1: /camp/lab/luscomben/home/users/capitac/miCLIP_UN1710_CS2_delta2/summarising_trna_mapping_style/tRNA_paper/NSUN2_miCLIP/demux_NNNCAATNN.fq.gz
    NSUN2_HEK293T_2: /camp/lab/luscomben/home/users/capitac/miCLIP_UN1710_CS2_delta2/summarising_trna_mapping_style/tRNA_paper/NSUN2_miCLIP/demux_NNNGGCGNN.fq.gz
    TRMT2A_miCLIP_1: /camp/lab/luscomben/home/users/capitac/miCLIP_UN1710_CS2_delta2/summarising_trna_mapping_style/tRNA_paper/TRMT2A_miCLIP/TRMT2A_FICC_rep1.fq.gz
    TRMT2A_miCLIP_2: /camp/lab/luscomben/home/users/capitac/miCLIP_UN1710_CS2_delta2/summarising_trna_mapping_style/tRNA_paper/TRMT2A_miCLIP/TRMT2A_FICC_rep2.fq.gz
# snRNA dominant
    SMB_human_1: /camp/home/capitac/capitac/ncawareclip/Data/Smb_mild_HEK293_rep1_ERR3450336.fq.gz
    SMB_human_2: /camp/home/capitac/capitac/ncawareclip/Data/Smb_mild_HEK293_rep2_ERR3450337.fq.gz
    PRPF8_human_1: /camp/home/capitac/capitac/ncawareclip/Data/PRP8_Hela_rep1_ERR2822467.fq.gz
    PRPF8_human_2: /camp/home/capitac/capitac/ncawareclip/Data/PRP8_Hela_rep2_ERR2822468.fq.gz
# Classic iCLIP
    TIA1_1: /camp/lab/luscomben/home/shared/projects/marc_char_peaks/raw_data/TIA1_iCLIP/demux_NNNGGTTNN.fq.gz
    TIA1_2: /camp/lab/luscomben/home/shared/projects/marc_char_peaks/raw_data/TIA1_iCLIP/demux_NNNTTGTNN.fq.gz
    PTBP1_1: /camp/home/capitac/capitac/ncawareclip/Data/ptbp1_4su_hek293_rep1_ERR1588764.fq.gz
    PTBP1_2: /camp/home/capitac/capitac/ncawareclip/Data/ptbp1_4su_hek293_rep2_ERR1588765.fq.gz
    HNRNPC_1: /camp/home/capitac/capitac/classic_iclip/hnrnpc_irclip_flynn/demux_5bc_NNNNNCGTGATNNN.fq.gz
    HNRNPC_2: /camp/home/capitac/capitac/classic_iclip/hnrnpc_irclip_flynn/demux_5bc_NNNNNACATCGNNN.fq.gz
    TDP-43_1: /camp/home/capitac/capitac/ncawareclip/Data/tardbp-293flp-1-20181129-ju_trimmed.fq.gz 
    TDP-43_2: /camp/home/capitac/capitac/ncawareclip/Data/tardbp-293flp-2-20181129-ju_trimmed.fq.gz
    

# Indexes generated by prepare-annotation workflow
rRNA_index: ../prepare-annotation/Human_hg38/rRNA/rRNA_index/rRNA_bowtie
mature_tRNA_index: ../prepare-annotation/Human_hg38/tRNA/all_tRNA_index/all_tRNA_bowtie
immature_tRNA_index: ../prepare-annotation/Human_hg38/tRNA/all_immature_tRNA_index/all_immature_tRNA_bowtie
mature_snRNA_index: ../prepare-annotation/Human_hg38/snRNA/all_snRNA_index/all_snRNA_bowtie
immature_snRNA_index: ../prepare-annotation/Human_hg38/snRNA/all_immature_snRNA_index/all_immature_snRNA_bowtie
canonical_snRNA_index: ../prepare-annotation/Human_hg38/snRNA/canonical_snRNA_index/canonical_snRNA_bowtie
mito_index: ../prepare-annotation/Human_hg38/mito_separated/Mito_star_index
repeats_index: ../prepare-annotation/Human_hg38/repeats/repeats_index/repeats_bowtie
genome_minus_mito_index: ../prepare-annotation/Human_hg38/mito_separated/genomeMinusMito_star_index

# Optional parameters
remove_duplicates_ncRNA: True
fraction_trnaisotype_merge: "0.9"