# Files for index generation and mapping #

# Sequences
big_rDNA_sequence: "--taxon human RNA45SN"
small_rDNA_sequence: "--taxon human RNA5S1"
mature_tRNA_sequence: http://gtrnadb.ucsc.edu/GtRNAdb2/genomes/eukaryota/Hsapi38/hg38-mature-tRNAs.fa
mature_snRNA_sequence: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_27/gencode.v27.transcripts.fa.gz
canonical_snRNA_sequences: ""
immature_tRNA_bed: ""
genome_annotation: ""
genome_sequence: ""

