configfile:"species-specific-configs/Base_config.yaml"

rule all:
    input:
        config["species"]+"/rRNA/rRNA_index/rRNA_bowtie.1.ebwt",
        config["species"]+"/snRNA/canonical_snRNA_index/canonical_snRNA_bowtie.1.ebwt",
        config["species"]+"/snRNA/snRNA_sequences/all_snRNA.fa"


# rDNA
rule download_rRNA:
    threads:
        1
    params:
        rRNA=config["rDNA_sequence"],
        outdir=config["species"]+"/rRNA/rRNA_sequences",
        cluster= '-N 1 -c 1 --mem=16G -t 00:30:00'
    output:
        fasta=config["species"]+"/rRNA/rRNA_sequences/rRNA.fa"
    shell:
        """
        cd {params.outdir}
        datasets download gene symbol {params.rRNA}
        unzip ncbi_dataset.zip
        mv ncbi_dataset/data/rna.fna rRNA.fa
        rm -r ncbi_dataset.zip ncbi_dataset README.md
        """

rule rRNA_bowtie_index:
    input:
        config["species"]+"/rRNA/rRNA_sequences/rRNA.fa"
    threads:
        4
    params:
        outdir=config["species"]+"/rRNA/rRNA_index/rRNA_bowtie",
        cluster= '-N 1 -c 1 --mem=16G -t 00:30:00',
        log=config["species"]+"/logs"
    output:
        index=config["species"]+"/rRNA/rRNA_index/rRNA_bowtie.1.ebwt"
    shell:
        """
        mkdir -p {params.log}
        (bowtie-build {input} {params.outdir}) > {params.log}/rRNA_bowtie.log
        """

# snRNA
# canonical snRNAs canonical_snRNA_sequences
rule download_canon_snRNA:
    threads:
        1
    params:
        snRNA=config["canonical_snRNA_sequences"],
        outdir=config["species"]+"/snRNA/snRNA_sequences",
        cluster= '-N 1 -c 1 --mem=16G -t 00:30:00'
    output:
        fasta=config["species"]+"/snRNA/snRNA_sequences/canonical_snRNA.fa"
    shell:
        """
        cd {params.outdir}
        datasets download gene symbol {params.snRNA}
        unzip ncbi_dataset.zip
        mv ncbi_dataset/data/rna.fna canonical_snRNA.fa
        rm -r ncbi_dataset.zip ncbi_dataset README.md
        """

rule canon_snRNA_bowtie_index:
    input:
        config["species"]+"/snRNA/snRNA_sequences/canonical_snRNA.fa"
    threads:
        4
    params:
        outdir=config["species"]+"/snRNA/canonical_snRNA_index/canonical_snRNA_bowtie",
        cluster= '-N 1 -c 1 --mem=16G -t 00:30:00',
        log=config["species"]+"/logs"
    output:
        index=config["species"]+"/snRNA/canonical_snRNA_index/canonical_snRNA_bowtie.1.ebwt"
    shell:
        """
        mkdir -p {params.log}
        (bowtie-build {input} {params.outdir}) > {params.log}/canonical_snRNA_bowtie.log
        """

# mature snRNAs all
rule download_all_snRNA:
    threads:
        1
    params:
        snRNA=config["mature_snRNA_sequence"],
        oneline_snRNA=config["mature_snRNA_sequence"].replace(".fa.gz",".oneline.fa"),
        outdir=config["species"]+"/snRNA/snRNA_sequences",
        cluster= '-N 1 -c 1 --mem=16G -t 00:30:00'
    output:
        fasta=config["species"]+"/snRNA/snRNA_sequences/all_snRNA.fa"
    shell:
        """
        cd {params.outdir}
        wget {params.snRNA}
        basename {params.snRNA} | gunzip
        ./scripts/makeFastaOneLine.sh
        basename {params.oneline_snRNA} | grep -w -A 1 snRNA --no-group-separator > all_snRNA.fa
        """

# immature snRNA (genomic flanks)

# tRNA



# chrM

# genome minus chrM

