
# The first rule in the document contains a list of all the deadend outputs expected
# from the pipeline, that is, every output that isn't used in a subsequent rule.
configfile:"species-specific-configs/Base_config.yaml"

rule all:
    input:
        "results/rRNA/rRNA_sequences/rRNA.fa"


# rDNA
rule download_rRNA:
    threads:
        1
    params:
        rRNA=config["big_rDNA_sequence"]
        outdir="results/rRNA/rRNA_sequences",
        cluster= '-N 1 -c 1 --mem=16G -t 00:30:00'
    output:
        index="results/rRNA/rRNA_sequences/rRNA.fa"
    shell:
        """
        datasets download gene symbol {params.rRNA}
        mv ncbi_dataset.zip {params.outdir}
        unzip {params.outdir}/ncbi_dataset.zip
        mv {params.outdir}/ncbi_dataset/data/rna.fna {params.outdir}/rRNA.fa
        rm -r {params.outdir}/ncbi_dataset.zip {params.outdir}/ncbi_dataset
        """

#ncbi_dataset/data/rna.fna
# snRNA
# canonical snRNAs
# mature snRNAs all
# immature snRNA (genomic flanks)

# tRNA



# chrM

# genome minus chrM

